# Generated by Django 4.2.4 on 2023-08-29 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('pass_hash', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('role', models.CharField(choices=[('student', 'Student')], default='student', max_length=10)),
            ],
        ),
    ]
