# Generated by Django 4.2.4 on 2023-08-30 07:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.AddField(
            model_name='instructor',
            name='expertise',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
