# Generated by Django 4.2.4 on 2023-08-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0002_alter_instructor_email_remove_instructor_expertise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='expertise',
        ),
        migrations.AddField(
            model_name='instructor',
            name='expertise',
            field=models.ManyToManyField(related_name='instructors', to='lotusedt.expertise'),
        ),
    ]
