# Generated by Django 4.2.4 on 2023-08-29 20:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0003_assignment_course_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='instructor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='username',
        ),
        migrations.AddField(
            model_name='instructor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
