# Generated by Django 4.2.4 on 2023-08-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0005_department_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='lotusedt.instructor'),
        ),
    ]
