# Generated by Django 4.2.4 on 2023-09-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0007_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
