# Generated by Django 4.2.4 on 2023-09-01 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0009_departmentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DepartmentCourse',
        ),
    ]
