# Generated by Django 4.2.4 on 2023-09-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusedt', '0010_enrollment_email_delete_departmentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='email',
        ),
    ]
